#!/bin/sh
set -eu

repo='/opt/git/pccbot-discord-gateway.git'

case "${SSH_ORIGINAL_COMMAND-}" in
  "git-receive-pack '$repo'")
    exec /usr/bin/git-receive-pack "$repo"
    ;;
  "git-upload-pack '$repo'")
    exec /usr/bin/git-upload-pack "$repo"
    ;;
  *)
    echo 'SSH command denied.' >&2
    exit 126
    ;;
esac
